### ISSUE TITLE
Add support for figures, tables and equation linking and numbering

### ISSUE THREAD

**Issue by palemieux** [SMPTE/html-pub#7]

**Comment by SteveLLamb** [comment]
Table numbering supports resolved in #14

**Comment by SteveLLamb** [comment]
Figure numbering support resolved in #15

**Comment by billredmann** [comment]
When a cross-reference (hyperlink) is inserted to a section/figure/table/equation, etc., can we prepend the cross-reference type (e.g., **Section** 3, **Figure** 2) automatically? Or should that remain in the prose of the text (which is a fine alternative right now). 

Will auto-numbering of numbered notes be supported, too? (could be a different enhancement issue, or could be left for manual management).

Whatever of the follow are not addressed with this issue could be peeled out into a separate issue(s):

Further enhancement:
Along the same line, annexes should be signaled as "**Annex** A", though treated as a kind of section for the purpose of TOC, but where annexes have no section number and automatic numbering handles the incrementing annex letter), perhaps as id="annex-topic-in-this-annex" so that in lieu of an annex being cross-referenced as "5" (or "Section 5"), it would appear in both the TOC and cross-references as "Annex A".

Still further enhancement:
Figures, Tables, etc., within annexes get a special numbering.  E.g., the first figure in Annex A would be "Figure A.1"

**Comment by SteveLLamb** [comment]
> so that in lieu of an annex being cross-referenced as "5" (or "Section 5"), it would appear in both the TOC and cross-references as "Annex A".

> Still further enhancement:
> Figures, Tables, etc., within annexes get a special numbering. E.g., the first figure in Annex A would be "Figure A.1

This all already is in place and works. 

The only portion that needs to be added is adding in "Section" automatically without it going into the headers themselves. This is up for debate, as direct links without that read just fine IMO (the word "section" is just fluff in the prose).

**Comment by SteveLLamb** [comment]
> The only portion that needs to be added is adding in "Section" automatically without it going into the headers themselves. This is up for debate, as direct links without that read just fine IMO (the word "section" is just fluff in the prose).

Removing "section" from prose as per ISO. 

Going to move equations to separate issue for v2.

**Comment by SteveLLamb** [comment]
Closing, all resolved, except v2 item (equation) as noted above.
